name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-ecr-repo:latest
    - name: Login to ECR Registry
      uses: docker/login-action@v1
        with:
          registry: manoj-v1.dkr.ecr.ap-south-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: push image to ECR AWS
      run: docker push my-ecr-repo:latest
