name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag manojku4/datasecurity:$(date +%s)
    - name: push image to DockerHub
      run: docker push manojku4/datasecurity:$(date +%s)
